version: '3.7'

services:
  my_movies_list_db:
    image: postgres
    container_name: my_movies_list_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movies_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: my_movies_list
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
